# Generated by Django 3.2.13 on 2022-06-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
